### ISSUE TITLE
Search doesn't return anything

### ISSUE THREAD

**Issue by MsftSux** [newagesoftwareLLC/newgrounds-mobile#1]
Search function fails to return anything.  This seems to occur after 1 succesful search.  No error message.

**Comment by MsftSux** [comment]
Extra detail on the issue, using the word "frog" will fail to return anything, but searching the word "frog " will reurn items.  Seems to need a space. For that item at least.

**Comment by erfg12** [comment]
Is this for iOS, Android, Windows or Kodi?
